# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-08 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='data_time',
            new_name='date_time',
        ),
    ]
